baseURL = "https://cv.tomy.me/"
defaultContentLanguage = "en"
publishDir = "public"
disableKinds = ["taxonomy"]

[params]
favicon = "favicon.png"
redirectPrint = true
renderKeywords = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
      author = "Chi-Wei (Tomy) Hsieh"
      keywords = [
        "Chi-Wei",
        "Tomy",
        "Hsieh",
        "CV",
        "Resume",
        "Curriculum Vitae",
      ]

  # [languages.zh-tw]
  #   languageName = "繁體中文 (台灣)"
  #   weight = 2
  #   [languages.zh-tw.params]
  #     author = "謝繼緯"

[blackfriday]
    extensions = ["hardLineBreak"]
