baseURL = "https://cv.tomy.me/"
defaultContentLanguage = "en"
publishDir = "docs"
theme = "Not-Just-Simple-CV"
title = "Tomy Hsieh"

[params]
favicon = "favicon.png"
googleAnalytics = "G-Z9FPV34PPF"
facebookPixel = "1165349783920085"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.zh-tw]
    languageName = "繁體中文 (台灣)"
    weight = 2
