baseURL = "https://cv.tomy.me/"
defaultContentLanguage = "en"
publishDir = "docs"
theme = "Not-Just-Simple-CV"
title = "Tomy Hsieh"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.zh-tw]
    languageName = "繁體中文 (台灣)"
    weight = 2
