baseURL = "https://cv.tomy.me/"
defaultContentLanguage = "en"
publishDir = "public"
title = "Tomy Hsieh"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
favicon = "favicon.png"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.zh-tw]
    languageName = "繁體中文 (台灣)"
    weight = 2

[blackfriday]
    extensions = ["hardLineBreak"]
